spring:
  datasource:
    driver-class-name: org.h2.Driver
    url:  jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  jackson:
    date-format: dd/MM/yyyy
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  flyway:
    enabled: true

spring.jackson:
   time-zone: GMT-3
   locale: pt-BR
   
user.locale: user.language=pt-BR
TZ: GMT-3    